# -*- coding: utf-8 -*-
"""Notebook execution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wfd06pB8Y1MMwVxgQjw3oSda1wSGn_c_

Import libraries
"""

import os
import papermill as pm
from google.cloud import logging
import datetime 
import time
import pytz

SERVICE_ACCOUNT_FILE = 'service_account/adroit-hall-301111-d83ccae0ab62.json'
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = SERVICE_ACCOUNT_FILE

"""Define parameters"""

today = datetime.datetime.now(pytz.timezone('Asia/Hong_Kong')).strftime('%Y%m%d')
timestamp = round(time.time())

job_name = 'test_papermill'
input_path = 'gs://papermill_test/input/test_fail.ipynb'
output_path = 'gs://papermill_test/output/test_fail-{}-{}.ipynb'.format(today,timestamp)

"""Instantiates a logging client"""

# Instantiates a logging client
logging_client = logging.Client()

# Retrieves a Cloud Logging handler based on the environment
# you're running in and integrates the handler with the
# Python logging module. By default this captures all logs
# at INFO level and higher
logging_client.get_default_handler()
logging_client.setup_logging()
logger = logging_client.logger(job_name)

"""Execute the notebook"""

try:
  pm.execute_notebook(input_path,output_path)
  logger.log_struct(
    {"job_name": job_name, "execution_status": "success", "message":""},
    severity='INFO')
except Exception as e:
  logger.log_struct(
    {"job_name": job_name, "execution_status": "failure", "message":str(e)},
    severity='ERROR')